services:
  - type: web
    name: emberlink-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 8000
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true
    plan: free
    region: oregon
    rootDir: backend

  - type: web
    name: emberlink-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    buildFilter:
      paths:
        - frontend/**
    autoDeploy: true
    plan: free
    region: oregon
